language: cpp

#dist: trusty

compiler:
- g++

os:
- osx

branches:
  only:
  - master
  - inst

before_install:
  - rvm get head
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install doxygen; else brew install doxygen; fi
  - aclocal
  - automake --add-missing
  - autoconf

script:
  - ./configure && make distcheck && make distclean
  - rm *.tar.gz
  - autoreconf && ./configure --disable-doxygen && DISTCHECK_CONFIGURE_FLAGS="--disable-doxygen" make distcheck && make distclean